services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5431:5432"

  api:
    build: .
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js && npm test"
    environment:
      DATABASE_URL: postgres://testuser:testpass@db:5432/testdb
    depends_on:
      - db
