name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 - Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3 - Install deps
      - name: Install dependencies
        run: npm ci

      # Step 4 - Lint
      #- name: Run ESLint
      #  run: npm run lint

      # Step 5 - Run tests
      - name: Run Tests
        run: npm test
